---
# Per environment values which override defaults in hmpps-contacts-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: contacts-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    FEATURE_EVENTS_SNS_ENABLED: true

  # This can be moved back into values.yml when all envs are configured with domain events secrets
  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
